#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 4
#SBATCH --ntasks-per-node 28
#SBATCH --cpus-per-task 1
#SBATCH --time 00:30:00
#SBATCH --partition veryshort
#SBATCH --reservation=COSC026662
#SBATCH --account=COSC026662
#SBATCH --output d2q9-bgk.out
#SBATCH --nodelist=compute104,compute105,compute106,compute107
#SBATCH --exclusive

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
mpirun ./d2q9-bgk input_128x128.params obstacles_128x128.dat
mpirun ./d2q9-bgk input_128x256.params obstacles_128x256.dat
mpirun ./d2q9-bgk input_256x256.params obstacles_256x256.dat
mpirun ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

# mpirun ./d2q9-bgk input_2048x2048.params obstacles_2048x2048.dat
# mpirun ./d2q9-bgk input_4096x4096.params obstacles_4096x4096.dat
# mpirun ./d2q9-bgk input_8192x8192.params obstacles_8192x8192.dat
# mpirun ./d2q9-bgk input_16384x16384.params obstacles_16384x16384.dat

# mpirun ./d2q9-bgk input_2048x1024.params obstacles_2048x1024.dat
# mpirun ./d2q9-bgk input_4096x1024.params obstacles_4096x1024.dat
# mpirun ./d2q9-bgk input_8192x1024.params obstacles_8192x1024.dat
# mpirun ./d2q9-bgk input_16384x1024.params obstacles_16384x1024.dat