#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 1
#SBATCH --time 00:01:00
#SBATCH --gres=gpu:1
#SBATCH --partition gpu
#SBATCH --account COSC026662
#SBATCH --output d2q9-bgk.out
#SBATCH --exclusive
#SBATCH --exclude gpu03

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`
echo GPU number: $CUDA_VISIBLE_DEVICES

export OCL_DEVICE=1

#! Run the executable
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

./d2q9-bgk input_2048x2048.params obstacles_2048x2048.dat
./d2q9-bgk input_4096x4096.params obstacles_4096x4096.dat
./d2q9-bgk input_8192x8192.params obstacles_8192x8192.dat
./d2q9-bgk input_16384x16384.params obstacles_16384x16384.dat