#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --ntasks 37
#SBATCH --cpus-per-task 1
#SBATCH --time 00:30:00
#SBATCH --partition veryshort
#SBATCH --reservation=COSC026662
#SBATCH --account=COSC026662
#SBATCH --output d2q9-bgk_37.out
#SBATCH --exclude=compute101,compute102,compute103,compute108,compute109,compute110,compute111,compute117,compute121,compute127,compute216,compute300
#SBATCH --exclusive

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
mpirun ./d2q9-bgk input_128x128.params obstacles_128x128.dat
mpirun ./d2q9-bgk input_128x256.params obstacles_128x256.dat
mpirun ./d2q9-bgk input_256x256.params obstacles_256x256.dat
mpirun ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat