#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 4
#SBATCH --ntasks 78
#SBATCH --cpus-per-task 1
#SBATCH --time 00:30:00
#SBATCH --partition veryshort
#SBATCH --reservation=COSC026662
#SBATCH --account=COSC026662
#SBATCH --output d2q9-bgk_78.out
#SBATCH --nodelist=compute106,compute107,compute108,compute110
#SBATCH --exclusive

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
mpirun ./d2q9-bgk input_128x128.params obstacles_128x128.dat
mpirun ./d2q9-bgk input_128x256.params obstacles_128x256.dat
mpirun ./d2q9-bgk input_256x256.params obstacles_256x256.dat
mpirun ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat