#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 4
#SBATCH --ntasks 36
#SBATCH --cpus-per-task 1
#SBATCH --time 00:30:00
#SBATCH --partition veryshort
#SBATCH --reservation=COSC026662
#SBATCH --account=COSC026662
#SBATCH --output d2q9-bgk.out
#SBATCH --nodelist=compute106,compute107,compute108,compute110
#SBATCH --exclusive

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
mpirun -gtool "advixe-cl -collect survey -project-dir mpi_roofline:0" ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
mpirun -gtool "advixe-cl -collect tripcounts -flop --enable-cache-simulation -project-dir mpi_roofline:0" ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat